### ISSUE TITLE
Tests and CI missing

### ISSUE THREAD

**Issue by rikhuijzer** [hhaensel/SPCSpectra.jl#2]
It would probably be good to add some tests and CI so that people can verify that your package works or at least get an idea of what it can do exactly.

**Comment by hhaensel** [comment]
I absolutely agree, but I didn't have the time for thorough testing yet.
I personally just needed to read one file version and thought it would be nice to have a starting point, so I gave it a go. If I find some time, I'll go for testing and supporting other formats. Maybe other people would also contribute 😉
